sonar.projectKey=bventurin_MTG_CREATION_APP
sonar.organization=bventurin


# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=MTG_CREATION_APP
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8