sonar.projectKey=bventurin_MTG_CREATION_APP
sonar.organization=bventurin

sonar.sources=deck_builder,card_recommender,accounts
sonar.exclusions=**/migrations/**,**/tests.py
sonar.tests=deck_builder,card_recommender,accounts
sonar.test.inclusions=**/tests.py
sonar.coverage.exclusions=**/__init__.py,**/admin.py,**/apps.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8