sonar.projectKey=bventurin_MTG_CREATION_APP
sonar.organization=bventurin

sonar.sources=.
sonar.exclusions=**/.venv/**,**/lint_venv/**,**/migrations/**,**/staticfiles/**,manage.py,**/tests.py
sonar.tests=.
sonar.test.inclusions=**/tests.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8